#! /bin/sh

###################################################################
#                            Funtions                             #
###################################################################

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

###################################################################
#                           Auto-Start                            #
###################################################################

# Run keybinds Deamon
pgrep -x sxhkd > /dev/null || sxhkd &

# Run picom 
picom --experimental-backends &

# Run Wallpaper
sh ~/.fehbg &

# Run display config
#sh ~/.config/bspwm/xrandr.sh &

# Run panels 
sh ~/.config/bspwm/polybar.sh &

# Fix X cursor
xsetroot -Vimix_White 28 &

###################################################################
#                         WINDOW RULES                            #
###################################################################

bspc monitor DVI-I-1 -d 1 2 3
bspc monitor VGA-0 -d 4 5 6  

rule Alacritty desktop='4' follow=on
rule firefox desktop='1' follow=on 
rule Spotify desktop='3' follow=on
rule Pcmanfm desktop='5' 
rule qBittorrent desktop='5' 
rule Sxiv desktop='2' state=floating follow=on
rule Arandr desktop='2' state=floating
rule Lxappearance desktop='2' follow=on
rule discord desktop='6'

###################################################################
#                      General CONFIG                             #
###################################################################

config top_padding 26
config left_padding 0
config right_padding 0
config bottom_padding 26

config border_width 1
config window_gap 10
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config paddingless_monocle true
config focus_follows_pointer true

config focused_border_color \#27f127
config normal_border_color \#1b1b1b
config active_border_color \#1b1b1b

